#!python3

# fmt: off

programs = [
    # terminal programs
    "git", "zsh", "tmux", "mousepad", "neovim", "xsel", "xclip", "ranger", "fzf",
    # additional non-essential terminal programs
    "github-cli","git-delta","yt-dlp", "ffmpeg", "pandoc", "texlive-core","postgresql", "gitui",
    "lazygit", "bat",
    # gui tools
    "mpv", "typora", "obsidian", "copyq", "megasync-bin", "syncthing", "simplescreenrecorder", 
    "feh", "zathura", "zathura-pdf-mupdf", "okular"
    # additional developer tools
    "docker", "meld"
    # fonts
    "noto-fonts-emoji", "noto-fonts-cjk",
    "libxft-bgra", # fix for the suckless terminal, st, crashing due to emojis
    "lldb" # used with my neovim dap plugin configuration
]
# fmt: on

additional_commands = [
    # rust
    """
    curl https://sh.rustup.rs -sSf | sh
    """,

    # oh my zsh
    """
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    """,

    # ranger icons
    """
    git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
    """,

    # wall papers
    """
    git clone https://gitlab.com/dwt1/wallpapers /home/ms/Pictures/wallpapers
    """,

    # alacrity color themes
    """
    REPO=https://github.com/eendroroy/alacritty-theme.git
    DEST="$HOME/.eendroroy-colorschemes"
    # Get colorschemes
    git clone $REPO $DEST
    # Create symlink at default colors location (optional)
    ln -s "$DEST/themes" "$HOME/.config/alacritty/colors"
    """,

    # cheat.sh - https://cht.sh/
    """
    curl https://cht.sh/:cht.sh |
    sudo tee /usr/local/bin/cht.sh &&
    sudo chmod +x /usr/local/bin/cht.sh
    """,

    # vim-plug
    """
    sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    """,

    # volta
    """
    curl https://get.volta.sh | bash
    """,

    # tmux plugin manager
    """
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    """,

    # pyenv
    """
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv
    cd ~/.pyenv && src/configure && make -C src
    """,

    # pnpm
    """
    curl -fsSL https://get.pnpm.io/install.sh | sh -
    """
]

npms = [
    "eslint",
    "prettier",
    "bash-language-server",
    "vim-language-server",
    "git-file-history", # htts://githistory.xyz
]

cargos = ["fastmod", "ripgrep", "exa", "br", "rmem", "sd"]

pips = [
    "git-fame",  # for count lines per contributer
    "autopep8",  # for fomatting python
    "black",     # for fomatting python
    "ueberzug",  # for ranger to view images
    "mdtoc",     # mainly for mobadarah/tajmeeaton
    "yt-dlp",    # youtube-dl fork with additional features and fixes
]
