#!python3

# NOTE: these are arch programs
# fmt: off
programs = [
    # terminal programs
    "git", "zsh", "tmux", "mousepad", "neovim", "xsel", "xclip", "exa", "ripgrep", "ranger", "fzf",
    # additional non-essential terminal programs
    "github-cli","git-delta","yt-dlp", "ffmpeg", "pandoc", "texlive-core","postgresql", "gitui",
    "lazygit",
    # gui tools
    "mpv", "typora", "obsidian", "copyq", "megasync-bin", "syncthing", "simplescreenrecorder", 
    "feh",
    # additional developer tools
    "docker",
    # fonts
    "noto-fonts-emoji", "noto-fonts-cjk"
]
# fmt: on

aur_programs = [
    "ytfzf",
]

additional_commands = [
    "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm",
    "curl https://sh.rustup.rs -sSf | sh",
    'sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"',
    "git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons",
    "git clone https://gitlab.com/dwt1/wallpapers /home/ms/Pictures/wallpapers",
    """
    REPO=https://github.com/eendroroy/alacritty-theme.git
    DEST="$HOME/.eendroroy-colorschemes"
    # Get colorschemes
    git clone $REPO $DEST
    # Create symlink at default colors location (optional)
    ln -s "$DEST/themes" "$HOME/.config/alacritty/colors"
    """,
    """
    curl https://cht.sh/:cht.sh |
    sudo tee /usr/local/bin/cht.sh &&
    sudo chmod +x /usr/local/bin/cht.sh
    """,
    """
    git clone https://github.com/arzzen/git-quick-stats.git && cd git-quick-stats
    sudo make install
    """,
]


npms = [
    "eslint",
    "prettier",
]

cargos = ["fastmod", "br"]

pips = [
    "git-fame",  # for count lines per contributer
    "autopep8",  # for fomatting python
    "black",    # for fomatting python
    "ueberzug",  # for ranger to view images
    "mdtoc",    # mainly for mobadarah/tajmeeaton
]
